"""add userid

Revision ID: 665f9536ef93
Revises: 879affc156f6
Create Date: 2026-02-24 00:31:10.714483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665f9536ef93'
down_revision = '879affc156f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('facts_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.alter_column('solution',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.alter_column('solution',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_constraint('facts_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
