"""Add userid to facts and rules

Revision ID: 879affc156f6
Revises: 
Create Date: 2026-02-06 03:02:21.469074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '879affc156f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')


    # ### end Alembic commands ###
